name: Build and Deploy Preview Web UI
concurrency: preview-${{ github.ref }}

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - 'ui/**'

permissions:
  contents: write

defaults:
  run:
    working-directory: ./ui

jobs:
  build-and-deploy-preview-web-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test

      - name: Build App & Run e2e tests
        run: npm run build

      - name: Deploy preview 🚀
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ui/build
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
