name: Build and Deploy UI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ui/**'

permissions:
  contents: write

defaults:
  run:
    working-directory: ./ui

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Test App
        run: npm run test

      - name: Build App
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ui/build
          branch: gh-pages
